### ISSUE TITLE
MS305E and MS308E Might be unstable

### ISSUE THREAD

**Issue by S1146468** [foxey/py-netgear-plus#160]
### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/foxey/py-netgear-plus/issues?q=is%3Aissue+label%3A%22Bug%22+).

### Describe the issue

@Primajin expanded the support for the MS305E and MS308E. 
This morning i saw that the integration in Home Assistant is not loading correctly. 
Below you can see the error log from Home Assistant.

### Reproduction steps

There is none, it just happened over time

### Debug logs

Logger: homeassistant.config_entries
Source: config_entries.py:769
First occurred: April 20, 2026 at 10:50:48 PM (3 occurrences)
Last logged: April 20, 2026 at 10:50:48 PM

Error setting up entry MS305E 10.12.144.26 for netgear_plus
Error setting up entry MS308E 10.12.144.23 for netgear_plus
Error setting up entry MS308E 10.12.144.25 for netgear_plus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 769, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/__init__.py", line 49, in async_setup_entry
    if not await gs_switch.async_setup():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 86, in async_setup
    if not await self.hass.async_add_executor_job(self._setup):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 68, in _setup
    self.api = get_api(host=self._host, password=self._password)
               ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 31, in get_api
    api.autodetect_model()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/site-packages/py_netgear_plus/__init__.py", line 124, in autodetect_model
    response = self._page_fetcher.request(
        method,
        url,
    )
  File "/usr/local/lib/python3.14/site-packages/py_netgear_plus/fetcher.py", line 321, in request
    if response.status_code == status_code_ok and not self._is_authenticated(
                                                      ~~~~~~~~~~~~~~~~~~~~~~^
        response
        ^^^^^^^^
    ):
    ^
  File "/usr/local/lib/python3.14/site-packages/py_netgear_plus/fetcher.py", line 242, in _is_authenticated
    if len(title) and title[0].text.lower() == "redirect to login":
                      ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by Primajin** [comment]
Good morning @S1146468, what version are you using? I'm on `v0.7.11pre1` of the HACS plugin and didn't encounter any issues so far 🤔 

<img width="1080" height="460" alt="Image" src="https://github.com/user-attachments/assets/026844b3-5808-4903-b49b-306255c9758e" />

<br>

<img width="1080" height="1731" alt="Image" src="https://github.com/user-attachments/assets/9ef90587-0840-41ab-95ec-69c58eeeb7b2" />

**Comment by S1146468** [comment]
That might be the issue, but only if the hacs plugin has different code to support the ms305e and ms308e.
My hacs version is v0.7.10 
I will update and check if v0.7.12pre changes anything.

**Comment by Primajin** [comment]
If I understand the dependencies correctly https://github.com/foxey/py-netgear-plus/ is doing the heavy lifting while https://github.com/ckarrie/ha-netgear-plus/ is exposing the above to home assistant. 
If my assumption is correct, then https://github.com/ckarrie/ha-netgear-plus/releases shows MS30xE support only from `v0.7.11pre1` onwards... 

Crossing my fingers that it works for you 🤞🏻

**Comment by S1146468** [comment]
Than should that be the issue, somehow it did work on v0.7.10
I have debug mode turned on, if the error happends again, I'll get back in to you. 
Thanks

**Comment by foxey** [comment]
Thanks for reporting this @S1146468, and thanks @Primajin for the quick triage!

As Primajin noted, MS30xE support in ha-netgear-plus landed in `v0.7.11pre1`, so updating should resolve the setup failure.

That said, the traceback reveals a genuine bug in `fetcher.py` — `title[0].text` should be guarded against `None` before calling `.lower()`. This can surface whenever the switch returns an unexpected response during authentication. I’ll open a fix for that separately so it doesn’t cause silent failures on other models too.

Please do report back once you’ve updated — happy to dig further if the issue persists.

*— Ada, AI assistant acting on behalf of [@foxey](https://github.com/foxey)*

**Comment by S1146468** [comment]
Thanks for the response @foxey, i did notice that the other models did stay online in home assistant. 
What happened is that my 2 MS308E's and the MS305E went offline but the GS305E and GS305EP stayed online so it looks like the problem is local at the ms30xE part. 
What i did find interesting is that all my MS30xE's went offline at the same time.

**Comment by foxey** [comment]
**Update:** The `AttributeError` caused by `script[0].text` being `None` in `_is_authenticated` has been fixed in [#161](https://github.com/foxey/py-netgear-plus/pull/161) and released as **py-netgear-plus v0.6.3**.

The fix has also been picked up in **ha-netgear-plus v0.7.11pre3** — updating to that pre-release should resolve the instability reported here.

*— Ada, AI assistant acting on behalf of [@foxey](https://github.com/foxey)*
